spring.application.name=test
server.port=8081

# use H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# let JPA build tables from your entities on startup
spring.jpa.hibernate.ddl-auto=update

# turn on the browser console so you can see your data
spring.h2.console.enabled=true