DROP TABLE IF EXISTS asset;
DROP TABLE IF EXISTS users;

CREATE TABLE center (
    centerId     BIGINT NOT NULL PRIMARY KEY,
    name         VARCHAR(13) NOT NULL,
    addressLine1 VARCHAR(40) NOT NULL,
    addressLine2 VARCHAR(30),
    city         VARCHAR(12) NOT NULL,
    state        VARCHAR(2) NOT NULL,
    postalCode   VARCHAR(5) NOT NULL
);

CREATE TABLE inventory (
    inventoryId BIGINT NOT NULL PRIMARY KEY,
    centerId    BIGINT,
    CONSTRAINT fk_inventory_center FOREIGN KEY (centerId) REFERENCES center (centerId)
);

CREATE TABLE asset (
    assetId     BIGINT NOT NULL PRIMARY KEY,
    inventoryId BIGINT,
    name        VARCHAR(15) NOT NULL,
    assetStatus VARCHAR(12) NOT NULL,
    CONSTRAINT fk_asset_inventory FOREIGN KEY (inventoryId) REFERENCES inventory (inventoryId)
);

CREATE TABLE loanee (
    participantId BIGINT NOT NULL PRIMARY KEY
);

CREATE TABLE loan (
    loanId        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assetId       BIGINT,
    participantId BIGINT,
    checkoutDate  DATE,
    dueDate       DATE,
    returnDate    DATE,
    loanStatus    VARCHAR(15) NOT NULL,
    CONSTRAINT fk_loan_asset FOREIGN KEY (assetId) REFERENCES asset (assetId),
    CONSTRAINT fk_loan_loanee FOREIGN KEY (participantId) REFERENCES loanee (participantId)
);

CREATE TABLE maintenance (
    maintenanceId     BIGINT NOT NULL PRIMARY KEY,
    assetId           BIGINT,
    issue             VARCHAR(40) NOT NULL,
    maintenanceStatus VARCHAR(15) NOT NULL,
    repairNotes       VARCHAR(100) NOT NULL,
    openedDate        DATE,
    completedDate     DATE,
    CONSTRAINT fk_maintenance_asset FOREIGN KEY (assetId) REFERENCES asset (assetId)
);

CREATE TABLE credentials (
    userId   BIGINT NOT NULL PRIMARY KEY,
    username VARCHAR(155) NOT NULL UNIQUE,
    password VARCHAR(155) NOT NULL,
    roleId   BIGINT,
    CONSTRAINT fk_credentials_role FOREIGN KEY (roleId) REFERENCES role (id)
);
